name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make catalog

    - name: Validate
      uses: joelanford/opm-validate@main
      with:
        catalog: catalog

    - name: Release
      if: github.event_name == 'push'
      uses: catalog-release-bot/catalog-release-bot@main
      with:
        catalogDir: catalog
        packageName: example-operator

